# Currently we're not able to include command line arguments
schema_version:
  - 1

simulation:
  vunit:
    - ./examples/verilog/uart/run.py
    - ./examples/vhdl/array/run.py
    - ./examples/vhdl/osvvm_integration/run.py

